name: sudoku
channels:
  - pytorch
  - defaults
dependencies:
  - numpy=1.19.1
  - pillow=7.2.0
  - pip=20.2.2
  - python=3.8.5
  - pytorch=1.5.1
  - torchvision=0.6.1
  - pip:
    - fonttools==4.15.0
    - matplotlib==3.3.2
    - opencv-python==4.4.0.44
    - scipy==1.5.2
